remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "dark"

title: "parroz4"
description: >-
  I am a computer enthusiast and always keep up to date with new technologies.
  I am also passionate about cars and sports in general, and I am always
  looking for something new to learn related to computers.

url: "https://parroz4.github.io"

paginate: 5
paginate_path: "/blog/page:num/"
permalink: /:categories/:title/
show_excerpts: true

include:
  - _pages

author:
  name: "Francesco Parrotta"
  avatar: "/assets/Selfie.jpg"
  bio: "Computer enthusiast, passionate about cars and sports."
  location: "Italy"
  email: "4github.envision799@aleeas.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/parroz4"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/francesco-parrotta-26aba4b1/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
